Fixed repo-manage script

diff --git a/repo-manage b/repo-manage
--- a/repo-manage
+++ b/repo-manage
@@ -4,6 +4,19 @@
 #
 # Script to manage a git repository containing Ansible roles
 #
+# Don't do anything weird with role names, as internally a '.' in the name
+# will be replaced with '_' which means that there could be some confusion
+# with role names.
+#
+# Also, only tested with https git urls, not ssh.
+#
+
+# =============================================================
+# global vars
+
+GITHUB_ACCOUNT=freckles-io
+
+
 # =============================================================
 # Helper functions
 
@@ -19,13 +32,67 @@ function error_exit {
     #			string containing descriptive error message
     #	----------------------------------------------------------------
 
+    echo ""
 	  error_output "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+    echo ""
 	  exit 1
 }
 
-function error_output() {
+function error_output {
     # log $1
     (>&2 echo "$@")
+}
+
+function clean_string {
+    eval "$1=$(echo "$2" | sed 's/[^a-zA-Z0-9_-]/_/g')"
+}
+
+function prepare_github_api {
+
+    GITHUB_USERNAME=`git config github.user`
+    if [ "$GITHUB_USERNAME" = "" ]; then
+        echo ""
+        echo "Could not find username, run 'git config --global github.user <username>'"
+        echo ""
+        exit 1
+    fi
+
+    if command_exists secret-tool; then
+        GITHUB_TOKEN=`secret-tool lookup server api.github.com user "$GITHUB_USERNAME" key password`
+        if [[ -z "$GITHUB_TOKEN" ]]; then
+            echo ""
+            echo "No github token found in keyring, please create one with access to repo functions ( https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/ ), then store it via:
+
+  secret-tool store --label='github_token' server api.github.com user "$GITHUB_USERNAME" key password"
+            echo ""
+            exit 1
+        fi
+
+    else
+        echo ""
+        echo "Could not find 'secret-tool' executable, please install (e.g. 'apt install libsecret-tools')"
+        echo ""
+        exit 1
+    fi
+
+}
+
+function fork_repo {
+
+    prepare_github_api
+
+    local repo_url_local="$2"
+
+    local repo_name=${repo_url_local##*/}
+    repo_name=${repo_name%.*}
+
+    local user_name=${repo_url_local%/*}
+    user_name=${user_name##*/}
+
+    echo "Forking repo to user account: $GITHUB_USERNAME"
+    curl -su "$GITHUB_USERNAME:$GITHUB_TOKEN" "https://api.github.com/repos/$user_name/$repo_name/forks" -d '' 2>&1 > /dev/null || error_exit "Could not fork repo '$repo_url_local' to user account '$GITHUB_USERNAME"
+
+    eval "$1=https://github.com/${GITHUB_USERNAME}/${repo_name}.git"
 }
 
 # =============================================================
@@ -56,13 +123,22 @@ function command_pull_upstream {
 
    if [[ "$#" -ne 1 ]]; then
       echo ""
-      echo "Illegal number of arguments: exactly one REPO_URL allowed."
+      echo "Illegal number of arguments: exactly one ROLE_NAME allowed."
       echo ""
       exit 1
    fi
 
-   role_name="$1"
-   echo "$role_name"
+   # reading path to role
+   while read -r line; do declare  $line; done <".role_repos"
+
+   clean_string role_key "$1"
+   role_path=${!role_key}
+   role_name=$(basename ${role_path})
+
+   # fetch updates
+   git fetch "${role_key}_upstream"
+
+   git subtree pull --prefix "${role_path}" "${role_key}_upstream" master --squash
 
 
 }
@@ -119,17 +195,12 @@ function command_add {
 
    repo_url="$1"
    echo "$repo_url"
-   role_name="$(basename $local_path)"
+   dir_name=$(basename ${local_path})
+   clean_string role_name "$dir_name"
 
    if [ "${fork}" = true ]; then
-      echo "forking repo not supported yet."
-      exit 2
-      # forking the repo
-      upstream_repo_username="geerlingguy"
-      upstream_repo_name="ansible-role-docker"
 
-      echo "Forking repo"
-      curl -u "$GITHUB_USERNAME:$GITHUB_TOKEN" "https://api.github.com/repos/$upstream_repo_username/$upstream_repo_name/forks" -d ''
+      fork_repo repo_url "$repo_url"
 
    fi
 
@@ -142,7 +213,6 @@ function command_add {
 
    echo "Added repositury '${repo_url}' (using alias '${upstream_alias}' at path: ${local_path}"
    echo "${role_name}=${local_path}" >> .role_repos
-
 }
 
 
@@ -151,33 +221,6 @@ function command_add {
 # VARS
 
 PROGNAME="repo-manage"
-GITHUB_ACCOUNT=freckles-io
-
-GITHUB_USERNAME=`git config github.user`
-if [ "$GITHUB_USERNAME" = "" ]; then
-  echo ""
-  echo "Could not find username, run 'git config --global github.user <username>'"
-  echo ""
-  exit 1
-fi
-
-if command_exists secret-tool; then
-   GITHUB_TOKEN=`secret-tool lookup server api.github.com user "$GITHUB_USERNAME" key password`
-   if [[ -z "$GITHUB_TOKEN" ]]; then
-      echo ""
-      echo "No github token found in keyring, please create one with access to repo functions ( https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/ ), then store it via:
-
-  secret-tool store --label='github_token' server api.github.com user "$GITHUB_USERNAME" key password"
-      echo ""
-      exit 1
-   fi
-
-else
-  echo ""
-  echo "Could not find 'secret-tool' executable, please install (e.g. 'apt install libsecret-tools')"
-  echo ""
-  exit 1
-fi
 
 # =============================================================
 # ARG PARSING
@@ -185,6 +228,7 @@ fi
 subcommand=$1
 shift
 
+git diff-index --quiet HEAD -- || error_exit "local git repository has modifications, not doing anything..."
 
 case "$subcommand" in
   add)
